name: main

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  check_app:
    runs-on: ubuntu-latest
    steps:
    - name: clone_project
      uses: actions/checkout@v3
    - name: prepare_env
      run: |
        sudo apt update
        sudo apt install gcc-multilib g++-multilib
    - name: compile
      run: make
    - name: append_path
      run: echo "`pwd`/bin" >> $GITHUB_PATH
    - name: compile_tests
      run: make test
    - name: run_test_1
      run: |
        cd test/bin
        helltracer32 ./test_1 -output ./test_1.csv -entry 0x401070 -start 0x4011ad -end 0x4011d6 --eip -mem [ebp-4:4]
        cat ./test_1.csv
