name: main

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  check_app:
    runs-on: ubuntu-latest
    steps:
    - name: clone_project
      uses: actions/checkout@v3
    - name: prepare_env
      run: |
        sudo apt update
        sudo apt install gcc-multilib g++-multilib
    - name: make
      run: make
    - name: append_path
      run: echo "`pwd`/bin" >> $GITHUB_PATH
    - name: prepare_tests
      run: make test
